const {
  KANIM_USERNAME,
  KANIM_PASSWORD,
  NODE_ENV,
  MONGO_URL,
  MONGO_DATABASE,
  MONGO_TEST_DATABASE,
  SENDGRID_API_KEY,
} = process.env;

module.exports = {
  KANIM_USERNAME,
  KANIM_PASSWORD,
  NODE_ENV,
  MONGO_URL,
  MONGO_DATABASE,
  MONGO_TEST_DATABASE,
  SENDGRID_API_KEY,
};
